# Generated by Django 2.1 on 2018-08-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GNAME', models.CharField(max_length=30, verbose_name='社團名稱')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GPM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(blank=True, max_length=15, null=True, verbose_name='職稱')),
                ('RM', models.CharField(blank=True, max_length=30, null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('GP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.GP', verbose_name='群組')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.CharField(max_length=10, unique=True)),
                ('CNAME', models.CharField(max_length=20)),
                ('ENAME', models.CharField(blank=True, max_length=100, null=True)),
                ('DEP', models.CharField(blank=True, max_length=30, null=True)),
                ('GRADE', models.CharField(blank=True, max_length=10, null=True)),
                ('EMAIL', models.EmailField(blank=True, max_length=254, null=True)),
                ('PHONE', models.CharField(blank=True, max_length=20, null=True)),
                ('EXT', models.CharField(blank=True, max_length=20, null=True)),
                ('ICN', models.CharField(blank=True, max_length=15, null=True)),
                ('ADDR', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='gpm',
            name='MEMBER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Member', verbose_name='成員'),
        ),
    ]
