# Generated by Django 2.1 on 2018-08-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('SID', models.CharField(max_length=10, unique=True)),
                ('CNAME', models.CharField(max_length=20)),
                ('ENAME', models.CharField(blank=True, max_length=100, null=True)),
                ('DEP', models.CharField(blank=True, max_length=30, null=True)),
                ('GRADE', models.CharField(blank=True, max_length=10, null=True)),
                ('EMAIL', models.EmailField(blank=True, max_length=254, null=True)),
                ('PHONE', models.CharField(blank=True, max_length=20, null=True)),
                ('EXT', models.CharField(blank=True, max_length=20, null=True)),
                ('ICN', models.CharField(blank=True, max_length=15, null=True)),
                ('ADDR', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
