# Generated by Django 2.1 on 2018-08-17 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("backend", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("CNAME", models.CharField(max_length=30, verbose_name="中文名稱")),
                (
                    "ENAME",
                    models.CharField(blank=True, max_length=200, null=True, verbose_name="英文名稱"),
                ),
                (
                    "CABBR",
                    models.CharField(blank=True, max_length=10, null=True, verbose_name="中文簡稱"),
                ),
                (
                    "EABBR",
                    models.CharField(blank=True, max_length=30, null=True, verbose_name="英文簡稱"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("CNAME", models.CharField(max_length=30, verbose_name="中文名稱")),
                (
                    "ENAME",
                    models.CharField(blank=True, max_length=200, null=True, verbose_name="英文名稱"),
                ),
                (
                    "CABBR",
                    models.CharField(blank=True, max_length=10, null=True, verbose_name="中文簡稱"),
                ),
                (
                    "EABBR",
                    models.CharField(blank=True, max_length=30, null=True, verbose_name="英文簡稱"),
                ),
                (
                    "COLLEGE",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.College",
                        verbose_name="學院",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="gp",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
        ),
        migrations.AlterField(
            model_name="gp",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="建立時間"),
        ),
        migrations.AlterField(
            model_name="gpm",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
        ),
        migrations.AlterField(
            model_name="gpm",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="建立時間"),
        ),
        migrations.AlterField(
            model_name="member",
            name="ADDR",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="住址"),
        ),
        migrations.AlterField(
            model_name="member",
            name="CNAME",
            field=models.CharField(max_length=20, verbose_name="中文姓名"),
        ),
        migrations.AlterField(
            model_name="member",
            name="DEP",
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="系所"),
        ),
        migrations.AlterField(
            model_name="member",
            name="ENAME",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="英文姓名"),
        ),
        migrations.AlterField(
            model_name="member",
            name="EXT",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="校內分機"),
        ),
        migrations.AlterField(
            model_name="member",
            name="GRADE",
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name="年級"),
        ),
        migrations.AlterField(
            model_name="member",
            name="ICN",
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="身份證字號"),
        ),
        migrations.AlterField(
            model_name="member",
            name="PHONE",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="手機"),
        ),
        migrations.AlterField(
            model_name="member",
            name="SID",
            field=models.CharField(max_length=10, unique=True, verbose_name="學號"),
        ),
        migrations.AlterField(
            model_name="member",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
        ),
        migrations.AlterField(
            model_name="member",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="修改時間"),
        ),
    ]
