# Generated by Django 2.1 on 2018-09-16 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0004_googlesheet"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPerms",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("edit", models.BooleanField()),
                (
                    "gp",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="backend.GP"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gp",
            name="users",
            field=models.ManyToManyField(
                related_name="perms", through="backend.UserPerms", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
