# Generated by Django 2.1 on 2018-09-14 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0004_googlesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='gp',
            name='edit',
            field=models.ManyToManyField(related_name='euser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gp',
            name='view',
            field=models.ManyToManyField(related_name='vuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
