# Generated by Django 2.1 on 2018-09-16 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20180916_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesheet',
            name='GP',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.GP'),
            preserve_default=False,
        ),
    ]
