# Generated by Django 2.1 on 2018-09-14 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0005_auto_20180914_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gp',
            name='edit',
        ),
        migrations.RemoveField(
            model_name='gp',
            name='view',
        ),
        migrations.AddField(
            model_name='gpm',
            name='edit',
            field=models.ManyToManyField(related_name='_gpm_edit_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gpm',
            name='view',
            field=models.ManyToManyField(related_name='_gpm_view_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
