# Generated by Django 2.1 on 2018-09-14 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20180914_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpm',
            name='edit',
        ),
        migrations.RemoveField(
            model_name='gpm',
            name='view',
        ),
    ]
