# Generated by Django 2.1 on 2018-09-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("backend", "0006_googlesheet_gp")]

    operations = [
        migrations.AddField(
            model_name="googlesheet",
            name="EMAIL",
            field=models.IntegerField(blank=True, null=True, verbose_name="EMAIL 在第幾欄"),
        )
    ]
