# Generated by Django 2.1 on 2018-09-14 12:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0010_auto_20180914_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='gp',
            name='view',
            field=models.ManyToManyField(related_name='viewuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
