# Generated by Django 2.1 on 2018-09-14 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0011_gp_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.BooleanField()),
                ('edit', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='gp',
            name='view',
        ),
        migrations.AddField(
            model_name='userperms',
            name='gp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.GP'),
        ),
        migrations.AddField(
            model_name='userperms',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gp',
            name='users',
            field=models.ManyToManyField(related_name='perms', through='backend.UserPerms', to=settings.AUTH_USER_MODEL),
        ),
    ]
