# Generated by Django 2.1 on 2018-09-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20180914_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userperms',
            old_name='gp',
            new_name='gp_id',
        ),
        migrations.RenameField(
            model_name='userperms',
            old_name='user',
            new_name='user_id',
        ),
    ]
