# Generated by Django 2.1 on 2018-09-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20180914_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userperms',
            old_name='gp_id',
            new_name='gp',
        ),
        migrations.RenameField(
            model_name='userperms',
            old_name='user_id',
            new_name='user',
        ),
    ]
