# Generated by Django 2.1 on 2018-10-28 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0007_googlesheet_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True, verbose_name='LINE User ID')),
                ('CNAME', models.CharField(max_length=20, verbose_name='中文姓名')),
                ('MEMBER', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Member', verbose_name='成員')),
            ],
        ),
    ]
