# Generated by Django 2.1 on 2018-10-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("line_bot", "0001_initial")]

    operations = [migrations.RemoveField(model_name="staff", name="MEMBER")]
