# Generated by Django 2.1 on 2018-12-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("line_bot", "0003_recvmsg")]

    operations = [
        migrations.AlterField(
            model_name="recvmsg",
            name="user_id",
            field=models.CharField(max_length=100, verbose_name="LINE User ID"),
        )
    ]
